steps:
  build:
    image: eclipse-temurin:17
    commands:
      - cd Pika-shu && bash gradlew assembleDebug
    environment:
      - ANDROID_HOME=/mnt/sdk
    volumes:
      - /home/woodpecker/sdk:/mnt/sdk